#include "core/case/CaseManifest.h"
#include "core/evidence/EvidenceBundleWriter.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTextStream>

#include <optional>

int main(int argc, char* argv[])
{
    QCoreApplication app(argc, argv);
    QTextStream out(stdout);
    QTextStream err(stderr);

    if (app.arguments().size() != 3)
    {
        err << "usage: evidence_bundle_writer_smoke <case.json> <output.json>\n";
        return 2;
    }

    const QString manifestPath = app.arguments().at(1);
    const QString outputPath = app.arguments().at(2);
    QString error;
    const std::optional<occtdebug::CaseManifest> manifest = occtdebug::CaseManifest::loadFromFile(manifestPath, &error);
    if (!manifest.has_value())
    {
        err << "failed to load manifest: " << error << "\n";
        return 3;
    }

    const QString caseRoot = QFileInfo(manifestPath).absolutePath();
    if (!occtdebug::EvidenceBundleWriter::writeBundle(*manifest, caseRoot, outputPath, &error))
    {
        err << "failed to write bundle: " << error << "\n";
        return 4;
    }

    QFile file(outputPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
    {
        err << "failed to reopen bundle: " << file.errorString() << "\n";
        return 5;
    }

    const QJsonDocument doc = QJsonDocument::fromJson(file.readAll());
    const QJsonObject root = doc.object();
    if (root.value(QStringLiteral("schema_version")).toInt() != 1)
    {
        err << "schema_version mismatch\n";
        return 6;
    }
    if (root.value(QStringLiteral("case_id")).toString() != manifest->caseId)
    {
        err << "case_id mismatch\n";
        return 7;
    }
    if (root.value(QStringLiteral("records")).toArray().isEmpty())
    {
        err << "records are empty\n";
        return 8;
    }
    if (root.value(QStringLiteral("source_links")).toArray().isEmpty())
    {
        err << "source_links are empty\n";
        return 9;
    }
    if (root.value(QStringLiteral("log_links")).toArray().isEmpty())
    {
        err << "log_links are empty\n";
        return 10;
    }
    bool foundSourceLine = false;
    bool foundLogLine = false;
    bool foundGeometryObject = false;
    for (const QJsonValue& value : root.value(QStringLiteral("records")).toArray())
    {
        const QJsonObject record = value.toObject();
        const QJsonObject location = record.value(QStringLiteral("location")).toObject();
        foundSourceLine = foundSourceLine || location.value(QStringLiteral("source_line")).toInt() == 2271;
        foundLogLine = foundLogLine || location.value(QStringLiteral("log_line")).toInt() == 6;
        foundGeometryObject = foundGeometryObject || location.value(QStringLiteral("geometry_object")).toString() == QStringLiteral("E125");
    }
    if (!foundSourceLine || !foundLogLine || !foundGeometryObject)
    {
        err << "evidence locations are incomplete\n";
        return 11;
    }
    const QJsonObject comparison = root.value(QStringLiteral("verification_comparison")).toObject();
    if (!comparison.value(QStringLiteral("available")).toBool())
    {
        err << "verification comparison is unavailable\n";
        return 12;
    }
    if (comparison.value(QStringLiteral("fail_delta")).toInt() >= 0)
    {
        err << "verification comparison did not improve\n";
        return 13;
    }
    const QJsonObject patch = root.value(QStringLiteral("patch")).toObject();
    if (patch.value(QStringLiteral("review_status")).toString() != QStringLiteral("Approved"))
    {
        err << "patch review status mismatch\n";
        return 14;
    }
    if (patch.value(QStringLiteral("review_items")).toArray().isEmpty())
    {
        err << "patch review items are empty\n";
        return 15;
    }
    if (patch.value(QStringLiteral("signoff_status")).toString() != QStringLiteral("blocked"))
    {
        err << "patch signoff status mismatch\n";
        return 16;
    }
    if (!patch.value(QStringLiteral("generation_status")).toString().contains(QStringLiteral("generated bytes=")))
    {
        err << "patch generation status mismatch\n";
        return 20;
    }
    if (root.value(QStringLiteral("verification_failures")).toArray().isEmpty())
    {
        err << "verification failures are empty\n";
        return 17;
    }
    if (root.value(QStringLiteral("verification_timing")).toObject().value(QStringLiteral("entries")).toArray().isEmpty())
    {
        err << "verification timing entries are empty\n";
        return 18;
    }
    if (root.value(QStringLiteral("testdiff_artifacts")).toObject().value(QStringLiteral("summary")).toString()
        != QStringLiteral("verification/testdiff_summary.txt"))
    {
        err << "testdiff artifact summary mismatch\n";
        return 19;
    }
    const QJsonObject testdiffArtifacts = root.value(QStringLiteral("testdiff_artifacts")).toObject();
    if (testdiffArtifacts.value(QStringLiteral("artifact_files")).toArray().size() < 3
        || testdiffArtifacts.value(QStringLiteral("artifact_counts")).toObject().value(QStringLiteral("performance")).toInt() != 1)
    {
        err << "testdiff detailed artifacts mismatch\n";
        return 21;
    }
    const QJsonObject artifactIndexSummary = testdiffArtifacts.value(QStringLiteral("artifact_index_summary")).toObject();
    if (testdiffArtifacts.value(QStringLiteral("artifact_index")).toObject().value(QStringLiteral("groups")).toArray().size() != 3
        || artifactIndexSummary.value(QStringLiteral("total_groups")).toInt() != 3
        || artifactIndexSummary.value(QStringLiteral("kind_group_counts")).toObject().value(QStringLiteral("performance")).toInt() != 1)
    {
        err << "testdiff artifact index summary mismatch\n";
        return 23;
    }
    const QJsonObject artifactAnalysis = testdiffArtifacts.value(QStringLiteral("artifact_analysis")).toObject();
    const QJsonObject artifactAnalysisSummary = artifactAnalysis.value(QStringLiteral("summary")).toObject();
    const QJsonObject generationPolicy = artifactAnalysis.value(QStringLiteral("generation_policy")).toObject();
    if (artifactAnalysisSummary.value(QStringLiteral("property_json_parsed")).toInt() != 1
        || artifactAnalysisSummary.value(QStringLiteral("performance_metrics")).toInt() != 1
        || generationPolicy.value(QStringLiteral("policy")).toString() != QStringLiteral("boundary_only")
        || generationPolicy.value(QStringLiteral("generation_performed")).toBool())
    {
        err << "testdiff artifact analysis summary mismatch\n";
        return 25;
    }
    const QJsonObject geometryDiff = root.value(QStringLiteral("geometry_diff")).toObject();
    if (!geometryDiff.value(QStringLiteral("available")).toBool()
        || geometryDiff.value(QStringLiteral("artifact")).toString() != QStringLiteral("artifacts/topology_compare.json")
        || geometryDiff.value(QStringLiteral("match_summary")).toObject().value(QStringLiteral("matched")).toInt() <= 0)
    {
        err << "geometry diff topology artifact mismatch\n";
        return 26;
    }

    out << "EVIDENCE_BUNDLE_SMOKE_OK " << QDir::toNativeSeparators(outputPath) << "\n";
    return 0;
}
